"use client";
import {useState,useEffect} from "react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Checkbox} from "@/components/ui/checkbox";
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from "@/components/ui/table";
import {toast} from "sonner";
import {Plus,Search,MapPin,CalendarDays,Clock,Users,ShieldCheck,Copy,ExternalLink,Settings,Check,CheckCircle2,X,ArrowLeft,LogOut,Download,Pin,LoaderCircle,Goal,Handshake} from "lucide-react";
import {Picker,Crest,Empty,Fixture,GameBadge,Vote,koreanDate,time,localDay,inputTime,fromInput,opponent} from "./teamkick";
import {currentVote,type Row} from "@/lib/model";
export function Matching(p:any){
 const {v,busy,setModal,run,captain}=p,[tab,setTab]=useState("open"),[query,setQuery]=useState(""),[format,setFormat]=useState("all"),[date,setDate]=useState("");
 const listings=v.listings.filter((g:Row)=>(format==="all"||g.format===format)&&(!date||localDay(g.start)===date)&&(g.region+" "+g.venue+" "+v.teams.find((t:Row)=>t.id===g.home)?.name).includes(query));
 const mine=v.requests.filter((r:Row)=>r.teamId===v.teamId),received=v.requests.filter((r:Row)=>v.games.some((g:Row)=>g.id===r.gameId&&g.home===v.teamId));
 const status:any={pending:"수락 대기",accepted:"매칭 확정",rejected:"거절됨",withdrawn:"철회됨",closed:"모집 종료",changed:"조건 변경 · 재신청 필요"};
 return <><Tabs value={tab} onValueChange={setTab}><TabsList className="mb-5 flex-wrap h-auto"><TabsTrigger value="open">모집 중</TabsTrigger><TabsTrigger value="mine">내가 신청한 매칭</TabsTrigger>{captain&&<TabsTrigger value="received">받은 신청 {received.filter((r:Row)=>r.status==="pending").length||""}</TabsTrigger>}<TabsTrigger value="confirmed">확정 매칭</TabsTrigger></TabsList></Tabs>
 {tab==="open"&&<><div className="filter-bar"><div className="row" style={{background:"white",border:"1px solid var(--border)",borderRadius:9,padding:"0 12px",flex:1,minWidth:180}}><Search size={17} className="muted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="지역, 구장 또는 팀 검색" style={{border:0}}/></div><input aria-label="경기 날짜" type="date" value={date} onChange={e=>setDate(e.target.value)} style={{width:160}}/><Picker value={format} onChange={setFormat} options={[{value:"all",label:"모든 경기 형식"},"11인제","8인제","6인제","5인제"]}/></div><div className="match-list-grid">{listings.map((g:Row)=>{const t=v.teams.find((t:Row)=>t.id===g.home),sent=mine.find((r:Row)=>r.gameId===g.id&&r.status==="pending");return <article key={g.id} className="panel listing"><div className="row between"><span className="badge badge-green">상대팀 모집 중</span><span className="small muted">{g.format} · {t?.level??"실력 협의"}</span></div><h3>{t?.name}</h3><span className="meta-pair"><CalendarDays/>{koreanDate(g.start)} {time(g.start)} – {time(g.end)}</span><span className="meta-pair"><MapPin/>{g.venue}</span><span className="meta-pair"><ShieldCheck/>{g.secured?"구장 확보 완료":"구장 협의 중"} · 비용 안내 {Number(g.cost).toLocaleString()}원</span><p className="data-note">{g.address}</p>{g.home===v.teamId?<button className="btn" onClick={()=>setModal({kind:"game",id:g.id})}>우리 팀 모집글 관리</button>:<button disabled={busy||!captain||!!sent} className="btn btn-green" onClick={()=>setModal({kind:"applyMatch",game:g})}>{sent?"신청 완료":captain?"매칭 신청하기":"주장만 신청할 수 있어요"}</button>}</article>})}</div>{!listings.length&&<section className="panel"><Empty title="조건에 맞는 모집글이 없어요" description="검색 조건을 바꾸거나 우리 팀의 경기를 등록해보세요."/></section>}</>}
 {(tab==="mine"||tab==="received")&&<section className="panel">{(tab==="mine"?mine:received).length?(tab==="mine"?mine:received).map((r:Row)=>{const g=[...v.games,...v.listings].find((g:Row)=>g.id===r.gameId);return <div className="notice" key={r.id}><div className="row between"><strong>{tab==="mine"?v.teams.find((t:Row)=>t.id===g?.home)?.name??"상대팀 경기":v.teams.find((t:Row)=>t.id===r.teamId)?.name}</strong><span className="badge">{status[r.status]??r.status}</span></div><p className="data-note">{g?koreanDate(g.start)+" · "+g.venue:"신청한 경기"}{r.message&&" · "+r.message}</p>{r.status==="pending"&&captain&&<div className="action-strip">{tab==="received"?<><button className="btn btn-green" disabled={busy} onClick={()=>run({type:"acceptMatch",teamId:v.teamId,gameId:r.gameId,requestId:r.id})}>매칭 수락</button><button className="btn" disabled={busy} onClick={()=>run({type:"rejectMatch",teamId:v.teamId,gameId:r.gameId,requestId:r.id})}>거절</button></>:<button className="btn" disabled={busy} onClick={()=>run({type:"withdrawMatch",teamId:v.teamId,gameId:r.gameId,requestId:r.id})}>신청 철회</button>}</div>}</div>}):<Empty title={tab==="mine"?"신청한 매칭이 없어요":"받은 신청이 없어요"}/>}</section>}
 {tab==="confirmed"&&<section className="panel">{v.games.filter((g:Row)=>g.away&&g.status!=="cancelled").map((g:Row)=><Fixture g={g} v={v} key={g.id} onClick={()=>setModal({kind:"game",id:g.id})}/>)}{!v.games.some((g:Row)=>g.away&&g.status!=="cancelled")&&<Empty title="확정된 매칭이 없어요"/>}</section>}</>
}
export function Management(p:any){
 const {v,team,onboarding,admin,busy,setModal,run,captain}=p,[query,setQuery]=useState("");
 if(admin)return <>{v.isOwner?<><div className="stats-grid" style={{marginBottom:24}}>{[{label:"등록 팀",v:v.teams.length},{label:"승인 대기",v:v.teams.filter((t:Row)=>t.status==="pending").length},{label:"활성 팀",v:v.teams.filter((t:Row)=>t.status==="active").length}].map(x=><div className="stat-card" key={x.label}><div className="stat-label">{x.label}</div><div className="stat-value">{x.v}</div></div>)}</div><div className="admin-grid">{v.teams.map((t:Row)=><section className="panel" key={t.id}><div className="row between"><h3>{t.name}</h3><span className={"badge "+(t.status==="pending"?"badge-orange":t.status==="active"?"badge-green":"badge-red")}>{({pending:"승인 대기",active:"승인 완료",rejected:"반려",suspended:"이용 정지"} as any)[t.status]}</span></div><p className="data-note">{t.region} · 신청자 {t.applicantName}</p><p className="small muted" style={{marginTop:12}}>{t.description}</p>{t.reason&&<p className="data-note">사유: {t.reason}</p>}<div className="action-strip">{t.status==="pending"&&<><button className="btn btn-green" disabled={busy} onClick={()=>run({type:"approveTeam",teamId:t.id})}>팀 승인</button><button className="btn" onClick={()=>setModal({kind:"reason",command:"rejectTeam",teamId:t.id,title:"팀 등록 반려"})}>반려</button></>}{t.status==="active"&&<button className="btn btn-danger" onClick={()=>setModal({kind:"reason",command:"suspendTeam",teamId:t.id,title:"팀 이용 정지"})}>이용 정지</button>}{t.status==="suspended"&&<button className="btn btn-green" disabled={busy} onClick={()=>run({type:"restoreTeam",teamId:t.id})}>이용 복구</button>}</div></section>)}</div><section className="panel" style={{marginTop:24}}><h2 className="view-heading">최근 운영 이력</h2>{v.audit.slice(0,12).map((a:Row)=><p className="data-note" key={a.id}>{localDay(a.at)} {time(a.at)} · {a.type} {a.reason?"· "+a.reason:""}</p>)}</section></>:<Empty title="서비스 운영자 권한이 필요해요"/>}</>;
 if(onboarding)return <section className="onboarding"><h1>함께 뛸 우리 팀을 연결하세요</h1><p>새 팀은 서비스 운영자가, 팀원 가입은 팀 주장이 승인합니다.</p><div className="two-col"><section className="panel"><ShieldCheck color="#168b53" size={27}/><h2 className="view-heading" style={{marginTop:18}}>새 팀 만들기</h2><p className="small muted" style={{lineHeight:1.7}}>팀 이름과 활동 지역을 등록하면 운영자가 신청을 확인해요.</p><button className="btn btn-green" style={{marginTop:20}} onClick={()=>setModal({kind:"createTeam"})}><Plus/>팀 등록 신청</button></section><section className="panel"><Users color="#168b53" size={27}/><h2 className="view-heading" style={{marginTop:18}}>기존 팀 가입하기</h2><p className="small muted" style={{lineHeight:1.7}}>아래에서 소속 팀을 찾고 가입을 신청하세요. 승인 후 일정이 보여요.</p></section></div>{v.ownTeams?.length>0&&<section className="panel" style={{marginTop:20}}><h3 className="view-heading">내 팀 등록 신청</h3>{v.ownTeams.map((t:Row)=><div className="notice" key={t.id}><div className="row between"><strong>{t.name}</strong><span className="badge">{({pending:"운영자 승인 대기",rejected:"반려",active:"승인 완료"} as any)[t.status]??t.status}</span></div>{t.reason&&<p className="data-note">{t.reason}</p>}</div>)}</section>}<section className="panel" style={{marginTop:20}}><div className="panel-title"><h2>가입할 팀 찾기</h2></div><input placeholder="팀 이름 또는 지역 검색" value={query} onChange={e=>setQuery(e.target.value)}/>{v.teams.filter((t:Row)=>t.status==="active"&&(t.name+" "+t.region).includes(query)).map((t:Row)=>{const m=v.mine?.find((m:Row)=>m.teamId===t.id);return <div className="notice" key={t.id}><div className="row between"><div><strong>{t.name}</strong><p className="data-note">{t.region}</p></div>{m?.status==="pending"?<button className="btn" disabled={busy} onClick={()=>run({type:"cancelJoin",teamId:t.id})}>승인 대기 · 신청 취소</button>:<button className="btn" onClick={()=>setModal({kind:"joinTeam",team:t})}>가입 신청</button>}</div></div>})}{!v.teams.some((t:Row)=>t.status==="active")&&<Empty title="아직 등록된 팀이 없어요"/>}</section>{v.setupNeeded&&<p className="data-note">서비스를 처음 설정하는 운영자이신가요? <button className="text-link" onClick={()=>setModal({kind:"setup"})}>운영자 초기 설정</button></p>}{v.isOwner&&<button className="btn" style={{marginTop:18}} onClick={()=>p.setView("admin")}>서비스 관리 열기</button>}</section>;
 const pending=v.members.filter((m:Row)=>m.status==="pending"),active=v.members.filter((m:Row)=>m.status==="active"),me=active.find((m:Row)=>m.userId===v.user.id);
 return <div className="gap-grid"><section className="panel"><div className="row between"><div className="team-header"><Crest name={team?.name} color={team?.color}/><div><h2>{team?.name}</h2><p>{team?.region} · {team?.format} · {team?.days}</p></div></div>{captain&&<button className="icon-button" aria-label="팀 정보 수정" onClick={()=>setModal({kind:"editTeam"})}><Settings size={19}/></button>}</div><p className="small muted" style={{lineHeight:1.8,marginTop:20}}>{team?.description}</p><div className="action-strip">{captain&&<button className="btn btn-green" onClick={()=>setModal({kind:"invite"})}><Plus/>팀원 초대</button>}<button className="btn" onClick={()=>setModal({kind:"profile",member:me})}>내 선수 정보 수정</button><button className="btn" onClick={()=>setModal({kind:"createTeam"})}>다른 팀 등록 신청</button><button className="btn" onClick={()=>setModal({kind:"findTeam"})}>다른 팀 가입</button></div>{team?.transferTo===me?.id&&<button className="btn btn-green" style={{marginTop:16}} disabled={busy} onClick={()=>run({type:"acceptCaptain",teamId:v.teamId,memberId:me.id})}>주장 인계 수락</button>}</section>
 {captain&&pending.length>0&&<section className="panel"><h2 className="view-heading">가입 승인 대기 <span className="badge badge-orange">{pending.length}</span></h2>{pending.map((m:Row)=><div key={m.id} className="attendance-item"><div><strong>{m.name}</strong><p className="data-note">{m.position} · 희망 등번호 {m.number}</p></div><div className="row"><button className="btn btn-green" disabled={busy} onClick={()=>run({type:"approveMember",teamId:v.teamId,memberId:m.id})}>승인</button><button className="btn" disabled={busy} onClick={()=>run({type:"rejectMember",teamId:v.teamId,memberId:m.id})}>거절</button></div></div>)}</section>}
 <section className="panel"><div className="panel-title"><h2>함께 뛰는 선수들 <span className="small muted">{active.length}명</span></h2></div><Table className="roster-table"><TableHeader><TableRow><TableHead>선수</TableHead><TableHead>등번호</TableHead><TableHead>포지션</TableHead><TableHead>역할</TableHead>{captain&&<TableHead>관리</TableHead>}</TableRow></TableHeader><TableBody>{active.map((m:Row)=><TableRow key={m.id}><TableCell><div className="row"><span className="player-avatar">{m.name.slice(-2)}</span><strong>{m.name}</strong></div></TableCell><TableCell>{m.number}</TableCell><TableCell>{m.position}</TableCell><TableCell><span className="badge">{m.role==="captain"?"주장":m.role==="manager"?"운영진":"팀원"}</span></TableCell>{captain&&<TableCell>{m.role!=="captain"&&<button className="text-link" onClick={()=>setModal({kind:"member",member:m})}>관리</button>}</TableCell>}</TableRow>)}</TableBody></Table></section>
 <section className="panel"><div className="panel-title"><h2>팀 공지</h2>{captain&&<button className="btn" onClick={()=>setModal({kind:"notice"})}><Plus/>공지 작성</button>}</div>{v.notices.map((n:Row)=><div className="notice" key={n.id} onClick={()=>setModal({kind:"noticeDetail",notice:n})}><p>{n.pinned&&<Pin className="pin"/>}{n.title}</p><span>{localDay(n.at)}</span></div>)}{!v.notices.length&&<p className="small muted">등록된 공지가 없어요.</p>}</section></div>
}
export function AppDialogs(p:any){
 const {modal,setModal,v,team,demo,busy,action,run,manager,captain}=p,[form,setForm]=useState<any>({}),[detailTab,setDetailTab]=useState("info"),[failure,setFailure]=useState(""),[confirm,setConfirm]=useState<any>(null),[install,setInstall]=useState<any>(null);
 const g=v.games?.find((g:Row)=>g.id===modal?.id),side=g?v.sides.find((s:Row)=>s.gameId===g.id):null;
 useEffect(()=>{const listener=(e:any)=>{e.preventDefault();setInstall(e)};window.addEventListener("beforeinstallprompt",listener);return()=>window.removeEventListener("beforeinstallprompt",listener)},[]);
 useEffect(()=>{setFailure("");if(!modal)return;setDetailTab("info");const game=v.games?.find((g:Row)=>g.id===modal.gameId),z=v.sides?.find((s:Row)=>s.gameId===modal.gameId);
  let f:any={};if(modal.kind==="createGame"){const d=new Date(Date.now()+7*864e5);f={start:inputTime(d.toISOString()).slice(0,10)+"T10:00",end:inputTime(d.toISOString()).slice(0,10)+"T12:00",format:"11인제",secured:true,needed:11,cost:0,listing:modal.listing??false,external:"",region:team?.region??""};}
  if(modal.kind==="changeGame")f={...game,start:inputTime(game.start),end:inputTime(game.end)};
  if(modal.kind==="attendance")f={values:{...(z.attendanceFinal?z.attendance:z.draft)}};
  if(modal.kind==="records"){const values=Object.fromEntries((z.roster??[]).filter((m:Row)=>z.attendance[m.id]).map((m:Row)=>[m.id,z.records[m.id]??{goals:0,assists:0}]));const score=game.home===v.teamId?game.result?.a:game.result?.b;f={values,ownGoals:z.ownGoals??0,unknownGoals:z.unknownGoals??Math.max(0,(score??0)-Object.values(values).reduce((sum:number,x:any)=>sum+x.goals,0))};}
  if(modal.kind==="result")f={own:game?.home===v.teamId?game.result?.a:game?.result?.b,opponent:game?.home===v.teamId?game.result?.b:game?.result?.a};
  if(modal.kind==="profile")f={...modal.member};if(modal.kind==="joinTeam")f={name:v.user?.name==="팀원"?"":v.user?.name,position:"MF",number:0};
  if(modal.kind==="editTeam")f={...team};if(modal.kind==="sideSettings")f={...z,deadline:inputTime(z.deadline)};if(modal.kind==="createTeam")f={region:"",format:"11인제",days:"일요일 오전",level:"중"};setForm(f);
 },[modal]);
 function field(k:string,value:any){setForm((f:any)=>({...f,[k]:value}))}
 async function save(c:any,after?:(o:any)=>void){setFailure("");try{const output=await action(c);if(after)after(output);else setModal(null)}catch(e:any){setFailure(e.message)}}
 function copy(value:string){navigator.clipboard.writeText(value).then(()=>toast.success("복사했어요.")).catch(()=>toast.error("복사할 수 없어요. 내용을 직접 선택해 복사해주세요."))}
 const label=(name:string,key:string,type="text",required=true)=><label>{name}<input type={type} required={required} value={form[key]??""} onChange={e=>field(key,type==="number"?e.target.value===""?"":Number(e.target.value):e.target.value)} min={type==="number"?0:undefined}/></label>;
 const submit=(name="저장하기")=><button type="submit" className="btn btn-green" disabled={busy}>{busy&&<LoaderCircle className="loader" size={16}/>} {name}</button>;
 const closed=()=>setModal(null),titles:any={setOpponent:"외부 상대팀 입력",findTeam:"가입할 팀 찾기",createGame:"새 경기 만들기",createTeam:"팀 등록 신청",joinTeam:"팀 가입 신청",profile:"내 선수 정보",editTeam:"팀 정보 수정",attendance:"실제 출석 확인",records:"골 · 어시스트 기록",result:"경기 결과 입력",changeGame:"경기 일정 변경",sideSettings:"우리 팀 경기 설정",notice:"팀 공지 작성",invite:"팀원 초대",applyMatch:"팀 매칭 신청",notifications:"알림",settings:"내 계정과 설정",setup:"운영자 초기 설정",reason:modal?.title,member:"팀원 관리",player:"선수 기록",noticeDetail:modal?.notice?.title,correct:"기록 정정 요청"};
 return <><Dialog open={!!modal} onOpenChange={o=>!o&&closed()}><DialogContent className={modal?.kind==="game"||modal?.kind==="records"?"sm:max-w-[720px] max-h-[90vh] overflow-y-auto rounded-2xl":"sm:max-w-[520px] max-h-[90vh] overflow-y-auto rounded-2xl"}><DialogHeader><DialogTitle>{modal?.kind==="game"?"경기 상세":titles[modal?.kind]??"팀킥"}</DialogTitle><DialogDescription>{modal?.kind==="game"&&g?koreanDate(g.start)+" · "+time(g.start):modal?.kind==="setup"?"전달받은 초기 설정 코드로 서비스 운영자를 등록합니다.":demo?"샘플 팀 공간입니다. 실제 데이터에는 반영되지 않습니다.":"우리 팀의 정보를 확인하고 관리하세요."}</DialogDescription></DialogHeader>
 {failure&&<p className="error-bar" role="alert">{failure}</p>}
 {modal?.kind==="game"&&g&&<><div className="detail-score"><div className="club"><Crest name={team?.name}/><strong>{team?.name}</strong></div><div style={{textAlign:"center"}}><GameBadge g={g}/><div className="score-big" style={{marginTop:12}}>{g.result?.status==="confirmed"?(g.home===v.teamId?g.result.a:g.result.b)+" : "+(g.home===v.teamId?g.result.b:g.result.a):"VS"}</div></div><div className="club"><Crest name={opponent(v,g)} color="orange"/><strong>{opponent(v,g)||"상대팀 미정"}</strong></div></div><Tabs value={detailTab} onValueChange={setDetailTab}><TabsList className="mb-4"><TabsTrigger value="info">경기 정보</TabsTrigger><TabsTrigger value="attendance">참여 현황</TabsTrigger><TabsTrigger value="record">경기 기록</TabsTrigger></TabsList>
 <TabsContent value="info"><div className="detail-meta"><span className="meta-pair"><CalendarDays/>{koreanDate(g.start)} · {time(g.start)} – {time(g.end)}</span><span className="meta-pair"><MapPin/>{g.venue}</span><p className="small">{g.address}</p><div className="row"><button className="btn" onClick={()=>copy(g.address)}><Copy/>주소 복사</button><a className="btn" target="_blank" rel="noopener noreferrer" href={"https://map.naver.com/p/search/"+encodeURIComponent(g.address)}><ExternalLink/>지도 보기</a></div><p>{g.format} · {g.secured?"구장 확보 완료":"구장 협의 중"} · 비용 안내 {Number(g.cost).toLocaleString()}원</p>{g.external&&<p>상대팀 직접 입력 · 팀 자체 기록</p>}{side?.meeting&&<p>집합 시간 {side.meeting}</p>}{side?.note&&<p style={{whiteSpace:"pre-wrap"}}>{side.note}</p>}</div>
 {g.status==="scheduled"&&<div style={{marginTop:18}}><Vote v={v} g={g} disabled={busy||team?.status!=="active"} onVote={(value:string)=>run({type:"vote",teamId:v.teamId,gameId:g.id,value})}/></div>}
 {g.change&&<div className="panel" style={{marginTop:15}}><strong>일정 변경 제안</strong><p className="data-note">{koreanDate(g.change.start)} {time(g.change.start)} · {g.change.venue}</p>{captain&&g.change.by!==v.teamId&&<div className="action-strip"><button className="btn btn-green" disabled={busy} onClick={()=>run({type:"confirmChange",teamId:v.teamId,gameId:g.id,proposalId:g.change.proposalId,agree:true})}>변경 수락 · 재투표</button><button className="btn" disabled={busy} onClick={()=>run({type:"confirmChange",teamId:v.teamId,gameId:g.id,proposalId:g.change.proposalId,agree:false})}>거절</button></div>}</div>}
 {manager&&g.status!=="cancelled"&&<div className="action-strip"><button className="btn" onClick={()=>setModal({kind:"sideSettings",gameId:g.id})}>팀 안내 수정</button>{captain&&!g.away&&!g.external&&g.listing!=="open"&&<button className="btn" onClick={()=>setModal({kind:"setOpponent",gameId:g.id})}>외부 상대팀 입력</button>}{captain&&g.status==="scheduled"&&Date.now()<Date.parse(g.start)&&<button className="btn" onClick={()=>setModal({kind:"changeGame",gameId:g.id})}>일정 변경{g.away?" 제안":""}</button>}{captain&&g.status==="scheduled"&&Date.now()>=Date.parse(g.end)&&<button className="btn btn-green" disabled={busy} onClick={()=>run({type:"completeGame",teamId:v.teamId,gameId:g.id})}>경기 완료 처리</button>}{captain&&!g.away&&!g.external&&g.status==="scheduled"&&<button className="btn" disabled={busy} onClick={()=>run({type:g.listing==="open"?"closeListing":"openListing",teamId:v.teamId,gameId:g.id})}>{g.listing==="open"?"모집 마감":"상대팀 모집"}</button>}{captain&&<button className="btn btn-danger" onClick={()=>setModal({kind:"reason",command:"cancelGame",teamId:v.teamId,gameId:g.id,title:"경기 취소"})}>경기 취소</button>}</div>}
 {g.status==="cancelled"&&<p className="data-note">취소 사유: {g.reason}</p>}</TabsContent>
 <TabsContent value="attendance"><div className="row" style={{flexWrap:"wrap",marginBottom:16}}>{[{key:"yes",label:"참여"},{key:"no",label:"미참여"},{key:"maybe",label:"미정"},{key:"none",label:"미응답"}].map(x=><span className="badge" key={x.key}>{x.label} {(side?.roster??[]).filter((m:Row)=>currentVote(side,m.id)===x.key).length}명</span>)}</div>{(side?.roster??[]).map((m:Row)=><div className="attendance-item" key={m.id}><span>{m.name} <small className="muted">#{m.number}</small></span><span className="badge">{side.attendanceFinal?(side.attendance[m.id]?"출석 확정":"불참 확정"):({yes:"참여 예정",no:"미참여",maybe:"미정",none:"미응답"} as any)[currentVote(side,m.id)]}</span></div>)}<p className="data-note">투표는 참석 의사입니다. 경기 완료 후 실제 참석 여부를 확인하면 출석에 반영됩니다.</p>{manager&&g.status==="completed"&&<button className="btn btn-green" style={{marginTop:18}} onClick={()=>setModal({kind:"attendance",gameId:g.id})}>{side.attendanceFinal?"출석 수정":"출석 확인 · 확정"}</button>}</TabsContent>
 <TabsContent value="record"><p className="status-line">{g.result?.status==="confirmed"?"경기 결과 확정":g.resultProposal?.status==="disputed"?"결과에 이견이 있어요":g.resultProposal?"상대팀 확인 대기":"경기 결과 미입력"}</p>{g.resultProposal&&<section className="panel"><strong>제안된 결과 {g.resultProposal.a} : {g.resultProposal.b}</strong><p className="data-note">{v.teams.find((t:Row)=>t.id===g.home)?.name} : {v.teams.find((t:Row)=>t.id===g.away)?.name} 기준</p>{captain&&g.resultProposal.by!==v.teamId&&<div className="action-strip"><button className="btn btn-green" disabled={busy} onClick={()=>run({type:"confirmResult",teamId:v.teamId,gameId:g.id,revision:g.resultProposal.revision,agree:true})}>결과 확인</button><button className="btn" disabled={busy} onClick={()=>run({type:"confirmResult",teamId:v.teamId,gameId:g.id,revision:g.resultProposal.revision,agree:false})}>결과가 달라요</button></div>}</section>}
 <Table className="roster-table"><TableHeader><TableRow><TableHead>선수</TableHead><TableHead>골</TableHead><TableHead>어시스트</TableHead></TableRow></TableHeader><TableBody>{Object.entries(side?.records??{}).map(([mid,rec]:any)=><TableRow key={mid}><TableCell>{side.roster?.find((m:Row)=>m.id===mid)?.name??v.members.find((m:Row)=>m.id===mid)?.name??"과거 선수"}</TableCell><TableCell>{rec.goals}</TableCell><TableCell>{rec.assists}</TableCell></TableRow>)}</TableBody></Table><p className="data-note">{side?.recordsFinal?"개인 기록 확정":"개인 기록 미확정"} · 상대 자책골 {side?.ownGoals??0} · 득점자 미상 {side?.unknownGoals??0}</p><div className="action-strip">{captain&&g.status==="completed"&&<button className="btn" onClick={()=>setModal({kind:"result",gameId:g.id})}>경기 결과 입력</button>}{manager&&g.status==="completed"&&side?.attendanceFinal&&g.result?.status==="confirmed"&&<button className="btn btn-green" onClick={()=>setModal({kind:"records",gameId:g.id})}>골 · 어시스트 입력</button>}<button className="btn" onClick={()=>setModal({kind:"correct",gameId:g.id})}>기록 정정 요청</button></div></TabsContent></Tabs></>}
 {modal?.kind==="setOpponent"&&<form className="form-grid" onSubmit={e=>{e.preventDefault();save({type:"setOpponent",teamId:v.teamId,gameId:modal.gameId,external:form.external})}}>{label("상대팀 이름","external")}{submit("상대팀 저장")}</form>}
 {modal?.kind==="createGame"&&<form className="form-grid" onSubmit={e=>{e.preventDefault();save({...form,type:"createGame",teamId:v.teamId,start:fromInput(form.start),end:fromInput(form.end)})}}><div className="two-col fields">{label("경기 시작","start","datetime-local")}{label("경기 종료","end","datetime-local")}</div>{label("구장 이름","venue")}{label("구장 전체 주소","address")}<div className="two-col fields"><label>경기 형식<Picker value={form.format} onChange={(x:string)=>field("format",x)} options={["11인제","8인제","6인제","5인제"]}/></label>{label("필요 인원","needed","number")}</div><div className="two-col fields">{label("지역","region")}{label("비용 안내 (원)","cost","number")}</div><label className="row"><Checkbox checked={form.secured} onCheckedChange={x=>field("secured",x===true)}/>구장을 확보했어요</label>{captain&&<label className="row"><Checkbox checked={form.listing} onCheckedChange={x=>{field("listing",x===true);if(x)field("external","")}}/>상대팀을 모집할게요</label>}{!form.listing&&label("외부 상대팀 이름 (없으면 미정)","external","text",false)}<label>팀 안내<textarea value={form.note??""} onChange={e=>field("note",e.target.value)}/></label>{submit("경기 등록하기")}</form>}
 {(modal?.kind==="createTeam"||modal?.kind==="editTeam")&&<form className="form-grid" onSubmit={e=>{e.preventDefault();save({...form,type:modal.kind,teamId:v.teamId})}}>{label("팀 이름","name")}{label("활동 지역","region")}{modal.kind==="createTeam"&&<><label>주 경기 형식<Picker value={form.format} onChange={(x:string)=>field("format",x)} options={["11인제","8인제","6인제","5인제"]}/></label>{label("활동 요일","days")}</>}<label>팀 소개<textarea value={form.description??""} onChange={e=>field("description",e.target.value)}/></label>{submit(modal.kind==="createTeam"?"운영자에게 등록 신청":"팀 정보 저장")}</form>}
 {(modal?.kind==="joinTeam"||modal?.kind==="profile")&&<form className="form-grid" onSubmit={e=>{e.preventDefault();save({...form,type:modal.kind==="profile"?"editProfile":"joinTeam",teamId:modal.team?.id??v.teamId})}}>{modal.team&&<strong>{modal.team.name}</strong>}{label("선수 이름","name")}<div className="two-col fields">{label("등번호","number","number")}<label>포지션<Picker value={form.position??"MF"} onChange={(x:string)=>field("position",x)} options={["GK","DF","MF","FW"]}/></label></div>{submit(modal.kind==="joinTeam"?"주장에게 가입 신청":"저장하기")}</form>}
 {modal?.kind==="attendance"&&<form className="form-grid" onSubmit={e=>{e.preventDefault();save({type:"attendance",teamId:v.teamId,gameId:modal.gameId,values:form.values})}}><p className="small muted">참여 투표를 기준으로 초안을 채웠어요. 실제 참석자를 확인해주세요.</p>{Object.entries(form.values??{}).map(([mid,value]:any)=><div className="attendance-item" key={mid}><label><Checkbox checked={value} onCheckedChange={x=>field("values",{...form.values,[mid]:x===true})}/>{v.sides.find((s:Row)=>s.gameId===modal.gameId)?.roster?.find((m:Row)=>m.id===mid)?.name}</label><span className="badge">{value?"출석":"불참"}</span></div>)}{submit("실제 출석 확정")}</form>}
 {modal?.kind==="records"&&<form className="form-grid" onSubmit={e=>{e.preventDefault();save({type:"records",teamId:v.teamId,gameId:modal.gameId,...form})}}><p className="small muted">출석이 확정된 선수의 골·어시스트를 입력하세요.</p><Table className="roster-table"><TableHeader><TableRow><TableHead>선수</TableHead><TableHead>골</TableHead><TableHead>어시스트</TableHead></TableRow></TableHeader><TableBody>{Object.entries(form.values??{}).map(([mid,rec]:any)=><TableRow key={mid}><TableCell>{v.sides.find((s:Row)=>s.gameId===modal.gameId)?.roster?.find((m:Row)=>m.id===mid)?.name}</TableCell>{["goals","assists"].map(k=><TableCell key={k}><input aria-label={mid+" "+k} type="number" min="0" max="99" className="record-input" value={rec[k]} onChange={e=>field("values",{...form.values,[mid]:{...rec,[k]:Number(e.target.value)}})}/></TableCell>)}</TableRow>)}</TableBody></Table><div className="two-col fields">{label("상대 자책골","ownGoals","number")}{label("득점자 미상","unknownGoals","number")}</div>{submit("개인 기록 확정")}</form>}
 {modal?.kind==="result"&&<form className="form-grid" onSubmit={e=>{e.preventDefault();save({type:"result",teamId:v.teamId,gameId:modal.gameId,...form})}}><div className="two-col fields">{label("우리 팀 득점","own","number")}{label("상대팀 득점","opponent","number")}</div><p className="data-note">앱 내 매칭 경기는 상대 주장 확인 후 확정됩니다. 외부팀 경기는 우리 팀 자체 기록으로 확정됩니다.</p>{submit("결과 제출")}</form>}
 {modal?.kind==="changeGame"&&<form className="form-grid" onSubmit={e=>{e.preventDefault();save({type:"changeGame",teamId:v.teamId,gameId:modal.gameId,...form,start:fromInput(form.start),end:fromInput(form.end)})}}><div className="two-col fields">{label("변경 시작","start","datetime-local")}{label("변경 종료","end","datetime-local")}</div>{label("구장 이름","venue")}{label("구장 주소","address")}{!form.away&&form.listing!=="open"&&label("외부 상대팀 이름","external","text",false)}{label("비용 안내","cost","number")}<p className="data-note">상대팀이 확정되었다면 상대 주장의 동의가 필요합니다. 변경 후 참여 여부를 다시 확인합니다.</p>{submit("일정 변경 제출")}</form>}
 {modal?.kind==="sideSettings"&&<form className="form-grid" onSubmit={e=>{e.preventDefault();save({type:"sideSettings",teamId:v.teamId,gameId:modal.gameId,note:form.note,meeting:form.meeting,needed:form.needed,...(Date.parse(fromInput(form.deadline))>Date.now()?{deadline:fromInput(form.deadline)}:{})})}}>{label("집합 시간·안내","meeting","text",false)}{label("필요 인원","needed","number")}{label("투표 마감","deadline","datetime-local")}<label>우리 팀 안내<textarea value={form.note??""} onChange={e=>field("note",e.target.value)}/></label>{submit()}</form>}
 {modal?.kind==="notice"&&<form className="form-grid" onSubmit={e=>{e.preventDefault();save({type:"createNotice",teamId:v.teamId,...form})}}>{label("공지 제목","title")}<label>내용<textarea required value={form.body??""} onChange={e=>field("body",e.target.value)}/></label><label className="row"><Checkbox checked={form.pinned??false} onCheckedChange={x=>field("pinned",x===true)}/>상단에 고정하기</label>{submit("공지 등록")}</form>}
 {modal?.kind==="noticeDetail"&&<><p style={{whiteSpace:"pre-wrap",lineHeight:1.85}}>{modal.notice.body}</p><p className="data-note">{localDay(modal.notice.at)}</p>{captain&&<button className="btn btn-danger" onClick={()=>setConfirm({title:"공지를 삭제할까요?",command:{type:"deleteNotice",teamId:v.teamId,noticeId:modal.notice.id}})}>공지 삭제</button>}</>}
 {modal?.kind==="applyMatch"&&<form className="form-grid" onSubmit={e=>{e.preventDefault();save({type:"applyMatch",teamId:v.teamId,gameId:modal.game.id,message:form.message})}}><strong>{koreanDate(modal.game.start)} {time(modal.game.start)}</strong><p className="small muted">{modal.game.venue} · 비용 안내 {Number(modal.game.cost).toLocaleString()}원</p><label>상대팀에 전달할 메시지<textarea value={form.message??""} onChange={e=>field("message",e.target.value)} placeholder="우리 팀 소개나 확인할 내용을 남겨주세요."/></label>{submit("이 조건으로 매칭 신청")}</form>}
 {modal?.kind==="reason"&&<form className="form-grid" onSubmit={e=>{e.preventDefault();setConfirm({title:modal.title+"을 진행할까요?",command:{type:modal.command,teamId:modal.teamId,gameId:modal.gameId,reason:form.reason}})}}><label>사유<textarea required value={form.reason??""} onChange={e=>field("reason",e.target.value)}/></label><button className="btn btn-danger" type="submit">확인</button></form>}
 {modal?.kind==="member"&&<><strong>{modal.member.name}</strong><div className="gap-grid"><button className="btn" disabled={busy} onClick={()=>save({type:"setRole",teamId:v.teamId,memberId:modal.member.id,role:modal.member.role==="manager"?"member":"manager"})}>{modal.member.role==="manager"?"운영진 권한 해제":"일정·기록 운영진 지정"}</button><button className="btn" onClick={()=>setConfirm({title:"이 선수에게 주장을 인계할까요?",command:{type:"transferCaptain",teamId:v.teamId,memberId:modal.member.id}})}>주장 인계 요청</button><button className="btn btn-danger" onClick={()=>setConfirm({title:"이 팀원을 내보낼까요?",command:{type:"removeMember",teamId:v.teamId,memberId:modal.member.id}})}>팀원 내보내기</button></div></>}
 {modal?.kind==="findTeam"&&<div className="gap-grid">{v.teams.filter((t:Row)=>t.status==="active"&&!v.mine.some((m:Row)=>m.teamId===t.id&&m.status==="active")).map((t:Row)=><div className="row between" key={t.id}><div><strong>{t.name}</strong><p className="data-note">{t.region}</p></div><button className="btn" disabled={v.mine.some((m:Row)=>m.teamId===t.id&&m.status==="pending")} onClick={()=>setModal({kind:"joinTeam",team:t})}>{v.mine.some((m:Row)=>m.teamId===t.id&&m.status==="pending")?"승인 대기":"가입 신청"}</button></div>)}<p className="data-note">가입할 수 있는 승인된 팀을 표시합니다.</p></div>}
 {modal?.kind==="invite"&&<><p className="small muted">초대받은 팀원은 로그인 후 주장의 가입 승인을 받아야 합니다. 링크는 7일간 유효합니다.</p>{form.link?<><input aria-label="초대 링크" readOnly value={form.link}/><button className="btn btn-green" onClick={()=>copy(form.link)}><Copy/>초대 링크 복사</button></>:<button className="btn btn-green" disabled={busy} onClick={()=>save({type:"invite",teamId:v.teamId},o=>field("link",window.location.origin+"/?invite="+encodeURIComponent(o.invite)))}>초대 링크 만들기</button>}{v.invites.filter((i:Row)=>i.active).map((i:Row)=><div className="row between" key={i.id}><span className="data-note">{localDay(i.expires)}까지 유효</span><button className="text-link" disabled={busy} onClick={()=>run({type:"revokeInvite",teamId:v.teamId,inviteId:i.id})}>링크 폐기</button></div>)}</>}
 {modal?.kind==="notifications"&&<>{v.notifications.length?[...v.notifications].reverse().map((n:Row)=><div className="notification-item" key={n.id}><strong className="small">{n.title}</strong><p>{n.body}</p><small>{koreanDate(n.at)} {time(n.at)}</small>{n.gameId&&v.games.some((g:Row)=>g.id===n.gameId)&&<button className="text-link" onClick={()=>setModal({kind:"game",id:n.gameId})}>경기 보기</button>}</div>):<Empty title="새로운 알림이 없어요" description="팀 가입과 경기 변경 소식을 이곳에서 확인할 수 있어요."/>}</>}
 {modal?.kind==="player"&&<><div className="team-header"><span className="player-avatar">{modal.player.name.slice(-2)}</span><div><h2>{modal.player.name}</h2><p>#{modal.player.number} · {modal.player.position}</p></div></div><div className="stats-grid" style={{gridTemplateColumns:"repeat(3,1fr)"}}>{["goals","assists","attend"].map((k,i)=><div className="stat-card" key={k}><span className="stat-label">{["골","어시스트","출석"][i]}</span><div className="stat-value">{modal.player[k]}</div></div>)}</div><p className="data-note">위 숫자는 선택한 기간의 기록입니다. 아래는 전체 경기 이력입니다.</p>{v.sides.filter((s:Row)=>s.records[modal.player.id]||s.attendance[modal.player.id]).map((s:Row)=>{const g=v.games.find((g:Row)=>g.id===s.gameId);return g?<div className="notice" key={s.id}><p>{koreanDate(g.start)} · {opponent(v,g)}</p><span>{s.attendance[modal.player.id]?"출석":"불참"} · {s.records[modal.player.id]?.goals??0}골 · {s.records[modal.player.id]?.assists??0}어시스트</span></div>:null})}</>}
 {modal?.kind==="correct"&&<form className="form-grid" onSubmit={e=>{e.preventDefault();save({type:"correctRequest",teamId:v.teamId,gameId:modal.gameId,message:form.message})}}><label>정정할 내용<textarea required value={form.message??""} onChange={e=>field("message",e.target.value)}/></label>{submit("기록 담당자에게 요청")}</form>}
 {modal?.kind==="setup"&&<form className="form-grid" onSubmit={e=>{e.preventDefault();save({type:"setupOwner",code:form.code})}}>{label("운영자 초기 설정 코드","code","password")}<p className="data-note">첫 로그인 순서로 권한을 부여하지 않습니다. 코드는 최초 운영자 등록에 한 번 사용합니다.</p>{submit("서비스 운영자로 등록")}</form>}
 {modal?.kind==="settings"&&<div className="gap-grid"><div className="row"><span className="avatar">{v.user?.name?.slice(-2)||"MY"}</span><strong>{demo?"샘플 팀 공간":v.user?.name||"로그인이 필요해요"}</strong></div>{demo?<button className="btn btn-green" onClick={()=>{p.setDemo(false);setModal(null);p.setView("team")}}>실제 우리 팀 공간으로</button>:<button className="btn" onClick={()=>{p.setDemo(true);setModal(null);p.setView("home")}}>샘플 팀 둘러보기</button>}{v.isOwner&&<button className="btn" onClick={()=>{p.setView("admin");setModal(null)}}><ShieldCheck/>서비스 관리</button>}{p.real?.setupNeeded&&p.real?.user&&<button className="btn" onClick={()=>{p.setDemo(false);setModal({kind:"setup"})}}>운영자 초기 설정</button>}{install?<button className="btn" onClick={async()=>{await install.prompt();setInstall(null)}}><Download/>홈 화면에 설치</button>:<p className="data-note">휴대폰 브라우저의 공유·메뉴에서 ‘홈 화면에 추가’를 선택해 앱처럼 열 수 있어요.</p>}{!demo&&v.role&&v.role!=="captain"&&<button className="btn btn-danger" onClick={()=>setConfirm({title:"현재 팀에서 탈퇴할까요?",command:{type:"leaveTeam",teamId:v.teamId}})}>팀 탈퇴</button>}{p.real?.user?<a className="btn" href="/signout-with-chatgpt?return_to=/" target="_top"><LogOut/>로그아웃</a>:<a className="btn btn-green" href={"/signin-with-chatgpt?return_to="+encodeURIComponent(typeof window!=="undefined"?"/"+window.location.search:"/")} target="_top">ChatGPT로 로그인</a>}<p className="data-note">팀킥 · 초기 팀 운영 버전<br/>앱 내 알림을 지원합니다. 휴대폰 푸시는 아직 연결되지 않았습니다.</p></div>}
 </DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={o=>!o&&setConfirm(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirm?.title}</AlertDialogTitle><AlertDialogDescription>팀 상태와 관련 기록에 반영됩니다. 내용을 확인한 후 진행해주세요.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>돌아가기</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>{const c=confirm.command;setConfirm(null);save(c)}}>확인</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>
}
